<?php

namespace Leafwrap\SocialConnects;

use Illuminate\Contracts\Http\Kernel;
use Illuminate\Support\ServiceProvider;

class SocialConnectServiceProvider extends ServiceProvider
{
    public function boot(Kernel $kernel)
    {
        $this->loadRoutesFrom(__DIR__ . '/routes/web.php');
        $this->loadViewsFrom(__DIR__ . '/views', 'social-connects');
        $this->mergeConfigFrom(__DIR__ . '/config/social-connects.php', 'social-connects');
        $this->loadMigrationsFrom(__DIR__ . '/migrations');
    }

    public function register(): void
    {
        $this->registerFacades();
        parent::register(); // TODO: Change the autogenerated stub
    }

    protected function registerFacades(): void
    {
        $this->app->singleton('SocialConnect', function ($app) {
            return new SocialConnect();
        });
    }
}
